# netlify.toml (en la raíz del repo)
[build]
  base = "frontend"        # entra a /frontend para instalar y build
  command = "npm run build"
  publish = "dist"         # publica /frontend/dist

# Forzar versión de Node en el build (evita sorpresas)
[build.environment]
  NODE_VERSION = "22"

# SPA fallback (rutas de Vue)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
